apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-app"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: {{ .Release.Name }}
          env:
          - name: SLEEP_TIME
            value: "60s"
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 9080
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 100
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 9080
              scheme: HTTP
            initialDelaySeconds: 50
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 100
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "/mnt/prestop.sh"]

          resources:
            limits:
              cpu: 2000m
              memory: 4000Mi
            requests:
              cpu: 600m
              memory: 2000Mi
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: prestop-volume
              mountPath: /mnt
      volumes:
        - name: prestop-volume
          configMap:
            name: sbox-prestop-script-config-with-sleep

