apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "external-alb-ingress"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alb-placeholder.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.certificateArn }}
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/group.name: "external-alb-group"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "instance"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
spec:
  rules:
    - host: "{{ .Release.Name }}-ext.{{ .Values.domain_name }}"
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: "{{ .Release.Name }}-alb-ingress-svc"
                port:
                  number: 80
