apiVersion: v1
kind: Service
metadata:
  name: "alb-ingress-svc"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alb-placeholder.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: "alb-ingress"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
