{{- if .Values.ingress.rules }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.cert-arn }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
spec:
  {{- range $host, $rules := .Values.ingress.rules }}
  - host: {{ $host }}
    http:
      paths:
      {{- range $rule := $rules }}
      - path: {{ $rule.path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $rule.service_name }}
            port:
              number: {{ $rule.service_port }}
      {{- end }}
  {{- end }}
{{- end }}
